export const GET_PRODUCT_DATA = 'GET_ALL_PRODUCT_DATA';
export const GET_PRODUCT_DATA_FAILED = 'GET_PRODUCT_DATA_FAILED';
export const FAVORITE_PRODUCTS = 'FAVORITE_PRODUCTS';
export const CHECKOUT_PRODUCTS = 'CHECKOUT_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const CLEAR_CHECKOUT = 'CLEAR_CHECKOUT';
export const REMOVE_CHECKOUT_ONE_PRODUCTS = 'REMOVE_CHECKOUT_ONE_PRODUCTS';
export const REMOVE_ALL_PRODUCT_FROM_CHECKOUT = 'REMOVE_ALL_PRODUCT_FROM_CHECKOUT'